Try to resizefs after resizing esxi disk
yunionio/onecloud pull request #8726
Opened 2020-11-10 09:07 UTC by rainzm

**这个 PR 实现什么功能/修复什么问题**:

- [x] 功能、bugfix描述
- [x] 冒烟测试

**是否需要 backport 到之前的 release 分支**:
- release/3.5

/area region esxiagent hostdeployer
/cc @wanyaoqi @swordqiu

2020-11-11 03:46 UTC, wanyaoqi requested changes

2020-11-17 06:39 UTC, rainzm commented on pkg/hostman/hostdeployer/deployserver/deployserver.go
> +			debug.PrintStack()
这是两个事吧 一个是打印recover返回的取值，一个是打印出调用栈。所以两行

2020-11-17 06:42 UTC, wanyaoqi commented on pkg/hostman/hostdeployer/deployserver/deployserver.go
> +			debug.PrintStack()
嗯，我的意思是统一用log.Errorf打印到标准错误

2020-11-17 06:44 UTC, rainzm commented on pkg/hostman/hostdeployer/deployserver/deployserver.go
> +			debug.PrintStack()
ok

2020-11-17 08:42 UTC, wanyaoqi commented
/lgtm
/approve

2020-11-17 08:44 UTC, merged